# Generated by Django 6.0.6 on 2026-07-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='grace_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutes after clock_in_start before marking as late'),
        ),
    ]
