runtime: python312
entrypoint: gunicorn spes_backend.wsgi:application --bind 0.0.0.0:$PORT

env_variables:
  DJANGO_SETTINGS_MODULE: "spes_backend.settings"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"

automatic_scaling:
  min_instances: 0
  max_instances: 1
